### ISSUE TITLE
get_display_resolution returns incorrect data on linux on a multi monitor setup

### ISSUE THREAD

**Issue by hiikion** [qb-0/pyMeow#14]
i have two 2560x1440 monitors and i run Nobara Linux 37.

But running `get_display_resolution` returns:
```
(5120, 1440)
```
get_screen_height and get_screen_width also return incorrect data:
```
5119 # get_screen_width output
1439 # get_screen_height output
```
But get_monitor_count does detect having 2 displays.

A possible temporary solution could be dividing the width and or height by the monitor quantity, depending on the monitor orientation.
But in the longer run, it would be better to rewrite the get_display_resolution function.

**Comment by hiikion** [comment]
The `xrandr` command seems to return correct display info for me,
so i wrote a function based on it:
```nim
import osproc, strutils, regex

proc getDisplayResolution: seq[(int,int)] =
    let 
        pattern = re"\d+x\d+"
        output = execCmdEx("xrandr | fgrep '*'").output
        matches = findAndCaptureAll(output, pattern)
    
    for match in matches:
        let spl = match.split("x")

        result.add((parseInt(spl[0]), parseInt(spl[1])))
```

**Comment by qb-0** [comment]
`get_screen_height` and `get_screen_width` returns the render size of the overlay. The overlay is initialized with one pixel smaller.
Is the overlay initialized over both displays then?

**Comment by hiikion** [comment]
> `get_screen_height` and `get_screen_width` returns the render size of the overlay. The overlay is initialized with one pixel smaller. Is the overlay initialized over both displays then?

Do you mean does it render on both displays?
Yeah
