### ISSUE TITLE
Overlay error "glGetnTexImage"

### ISSUE THREAD

**Issue by IagoBeuller** [qb-0/PyMeow#14]
On running the "overlay_test.py" I got this error:
`overlay = pm.overlay_init()

nimpy.LibraryError: Unexpected error encountered: could not find symbol: glGetnTexImage`

**Note:** I'm running on Windows 11, Python 3.8.10 (64 bit).

**Comment by IagoBeuller** [comment]
By the way:
 `nimble -y install winim nimgl nimpy regex
Downloading https://github.com/khchen/winim using git
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 129
        ... Command: git clone --recursive --depth 1 -b 3.8.0 https://github.com/khchen/winim C:\Users\Iago Beuller\AppData\Local\Temp\nimble_6296\githubcom_khchenwinim

        ... Output: fatal: Too many arguments.
        ... usage: git clone [<options>] [--] <repo> [<dir>]
        ...     -v, --verbose         be more verbose
        ...     -q, --quiet           be more quiet
        ...     --progress            force progress reporting
        ...     --reject-shallow      don't clone shallow repository
        ...     -n, --no-checkout     don't create a checkout
        ...     --bare                create a bare repository
        ...     --mirror              create a mirror repository (implies bare)
        ...     -l, --local           to clone from a local repository
        ...     --no-hardlinks        don't use local hardlinks, always copy
        ...     -s, --shared          setup as shared repository
        ...     --recurse-submodules[=<pathspec>]
        ...                           initialize submodules in the clone
        ...     --recursive ...       alias of --recurse-submodules
        ...     -j, --jobs <n>        number of submodules cloned in parallel
        ...     --template <template-directory>
        ...                           directory from which templates will be used
        ...     --reference <repo>    reference repository
        ...     --reference-if-able <repo>
        ...                           reference repository
        ...     --dissociate          use --reference only while cloning
        ...     -o, --origin <name>   use <name> instead of 'origin' to track upstream
        ...     -b, --branch <branch>
        ...                           checkout <branch> instead of the remote's HEAD
        ...     -u, --upload-pack <path>
        ...                           path to git-upload-pack on the remote
        ...     --depth <depth>       create a shallow clone of that depth
        ...     --shallow-since <time>
        ...                           create a shallow clone since a specific time
        ...     --shallow-exclude <revision>
        ...                           deepen history of shallow clone, excluding rev
        ...     --single-branch       clone only one branch, HEAD or --branch
        ...     --no-tags             don't clone any tags, and make later fetches not to follow them
        ...     --shallow-submodules  any cloned submodules will be shallow
        ...     --separate-git-dir <gitdir>
        ...                           separate git dir from working tree
        ...     -c, --config <key=value>
        ...                           set config inside the new repository
        ...     --server-option <server-specific>
        ...                           option to transmit
        ...     -4, --ipv4            use IPv4 addresses only
        ...     -6, --ipv6            use IPv6 addresses only
        ...     --filter <args>       object filtering
        ...     --remote-submodules   any cloned submodules will use their remote-tracking branch
        ...     --sparse              initialize sparse-checkout file to include only files at root`

**Comment by qb-0** [comment]
> I update my NVidia Drivers Card, I also runned Driver Booster, I installed "https://developer.nvidia.com/opengl-driver", and the problem isn't solved.

Interesting. Not sure what exactly causes that as I'm also not able to reproduce it. Which graphic card do you got?
The nimble issue isn't pymeow related. Check if git is able to clone repos. Otherwise create a issue on https://github.com/nim-lang/nimble/issues

**Comment by IagoBeuller** [comment]
GTX 1650, notebook version.

**Comment by qb-0** [comment]
This has been solved on discord:
The notebook was using the onboard graphic card.
