### ISSUE TITLE
Not working on ubuntu 20.04 

### ISSUE THREAD

**Issue by NoctisNebula** [qb-0/PyMeow#16]
Sadly this doesnt seem to be working on the official recommended ubuntu version: 
Getting this error:
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found 

Probably cant be deal with without changing os or code..

**Comment by qb-0** [comment]
Seems like Ubuntu 20.04 still uses some old version of libc. You can easily check it with `ldd --version`
Guess the easiest way is to compile pymeow yourself instead to upgrade your os.
