### ISSUE TITLE
垃圾包，别用 全是坑！

### ISSUE THREAD

**Issue by bloodrose00** [qb-0/pyMeow#18]

**Comment by bloodrose00** [comment]
你tm 自己那破包一堆毛病，自己不改，还tm逼逼赖赖，崩溃在你的pyd了，你tm问我提供什么？我说的不够明白？
你自己看看你的仓库，你这个pyMeow要是内存读写好用，你自己有欠欠的单独写个python mem-ctypes？你不会调自己的包？
完事还tm欠欠的去人家pymem的仓库里 显摆？你这两下子 你显摆个j8？显得你会写代码？

**Comment by bloodrose00** [comment]
瞎j8缝一堆有的没的的包，结果最关键的部分都不可用，花里胡哨整一堆，显你会调包是吗？

**Comment by bloodrose00** [comment]
raylib和ctypes 自己写 也比你这个破比nim靠谱，什么j8垃圾语言

**Comment by qb-0** [comment]
We can't offer a chinese support.
