### ISSUE TITLE
Font initialisation without a overlay 

### ISSUE THREAD

**Issue by NyshMy** [qb-0/PyMeow#19]
nimpy.Exception: Unexpected error encountered: Font initialisation without a overlay 

exp pymeow.font_init(0,"simsun")

**Comment by qb-0** [comment]
Called `overlay_init(target: string = "Fullscreen", exitKey: int = 0x23 (END), borderOffset: int = 25) -> Overlay` before?

**Comment by NyshMy** [comment]
If I want to draw text in the game window, how can I call it? Can I give an example? Thank you very much

**Comment by qb-0** [comment]
```python
from pymeow import *

overlay = overlay_init()
font = font_init(20, "Impact")

while overlay_loop(overlay):
    font_print(font, overlay["midX"], overlay["midY"], "Hello World", rgb("red"))
```

**Comment by NyshMy** [comment]
I think pymeow is a very powerful and easy-to-use memory modification library. Thank the author very much. It would be better if there was one to apply for memory and free memory
