### ISSUE TITLE
pointer_chain_32

### ISSUE THREAD

**Issue by ubiyca** [qb-0/pyMeow#19]
"pointer_chain_32" doesn't work or am I doing something wrong?

When I try to do this, I get the error 
"TypeError: unable to convert python object to seq[int]" or "TypeError: unable to convert python object to int"

**Comment by qb-0** [comment]
Please provide some code which you used to reproduce the issue. 

Also you can add a screenshot from cheat engine and the pointer.

**Comment by ubiyca** [comment]
`import pyMeow as pm

health = 0x136C8B8
process = pm.open_process("CoDWaW.exe")
base_address = pm.get_module(process, "CoDWaW.exe")["base"]
hp = pm.pointer_chain_32(process, base_address, health) 

print(hp)`

![Screenshot12](https://github.com/qb-0/pyMeow/assets/69876513/702a37ba-ae58-43bf-9326-c3626c551d47)

**Comment by qb-0** [comment]
Well that's not a pointer chain. Just read the value directly.

```python
import pyMeow as pm

health = 0x136C8B8
process = pm.open_process("CoDWaW.exe")
base_address = pm.get_module(process, "CoDWaW.exe")["base"]
hp = pm.r_int(process, base_address + health)
print(hp)
```
