### ISSUE TITLE
mouse_move  bugs

### ISSUE THREAD

**Issue by 331841003** [qb-0/pyMeow#20]
Unless using your hand to move the mouse, 
executing 'mouse_move' after the second attempt will result in an error distance

**Comment by qb-0** [comment]
How to reproduce the issue? I've tried it with following code but seems like everything is working fine.

```python
import pyMeow as pm
from time import sleep

for i in range(1000):
    sleep(0.5)
    pm.mouse_move(i, i)
```

**Comment by 331841003** [comment]
Run the follow code.for i in range(1,10):
   time.sleep(0.5)
   pm.mouse_move(20,20)
   print(pm.mouse_position())
The result:

&nbsp;


临轩听水?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月1日(星期六) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qb-0/pyMeow] mouse_move  bugs (Issue #20)





 
How to reproduce the issue? I've tried it with following code but seems like everything is working fine.
 import pyMeow as pm from time import sleep for i in range(1000):     sleep(0.5)     pm.mouse_move(i, i)

**Comment by 331841003** [comment]
Code:for i in range(1,10):
   time.sleep(0.5)
   pm.mouse_move(20,20)
   print(pm.mouse_position())Output:{'x': 1237.0, 'y': 582.0} {'x': 1277.0, 'y': 622.0} {'x': 1317.0, 'y': 661.0} {'x': 1356.0, 'y': 701.0} {'x': 1396.0, 'y': 741.0} {'x': 1436.0, 'y': 780.0} {'x': 1475.0, 'y': 820.0} {'x': 1515.0, 'y': 860.0} {'x': 1555.0, 'y': 899.0}The version 1.43.25&nbsp;


临轩听水?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月1日(星期六) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qb-0/pyMeow] mouse_move  bugs (Issue #20)





 
How to reproduce the issue? I've tried it with following code but seems like everything is working fine.
 import pyMeow as pm from time import sleep for i in range(1000):     sleep(0.5)     pm.mouse_move(i, i)

**Comment by qb-0** [comment]
Thanks. Has been fixed:

```python
pm.mouse_move(0, 0)
for i in range(5):
    sleep(1)
    print(pm.mouse_position())
    pm.mouse_move(20, 20, True)
```

Output:
```
{'x': 0.0, 'y': 0.0}
{'x': 20.0, 'y': 20.0}
{'x': 40.0, 'y': 40.0}
{'x': 60.0, 'y': 60.0}
{'x': 80.0, 'y': 80.0}
```
