### ISSUE TITLE
slow aobscan

### ISSUE THREAD

**Issue by NyshMy** [qb-0/PyMeow#23]
I found that aobscan is slow in searching 64 processes. By the way, can the fast call of C + + be realized by Nim language?

**Comment by qb-0** [comment]
How exactly did you called `aob_scan`. If the `moduleName` argument isn't correct you will do a process scan. Modulescan's should be fast enough. 

But yes I'm still working on the aob scan.

Yes, Nim as a fastcall pragma.

**Comment by NyshMy** [comment]
> 你到底是怎么打电话`aob_scan`的。如果`moduleName`参数不正确，您将进行进程扫描。Modulescan 的速度应该足够快。
> 
> 但是，是的，我仍在进行 aob 扫描。
> 
> 是的，Nim 作为 fastcall 编译指示。

The module is correct. I suspect it is because of the 64 bit process. The 32-bit search is very fast. I hope to encapsulate a fastcall method, because it seems troublesome to implement a fast stack in Python
