### ISSUE TITLE
AttributeError: module 'pyMeow' has no attribute 'get_display_resolution'

### ISSUE THREAD

**Issue by Douilol** [qb-0/pyMeow#25]
![Capture d’écran 2023-07-18 121809](https://github.com/qb-0/pyMeow/assets/106202984/ae976f16-7c49-4751-9f27-2a9fa15c7836)

**Comment by qb-0** [comment]
Try to reinstall pyMeow. Might be something wrong with your installation.

**Comment by Douilol** [comment]
> Try to reinstall pyMeow. Might be something wrong with your installation.

I already did this. it doesn't work

**Comment by qb-0** [comment]
Whats the output of `python -c "import sys;print(sys.version);import pyMeow;print(pyMeow.__dir__())"`?

Also make sure that you installed the zip file on the release page.
