### ISSUE TITLE
call error

### ISSUE THREAD

**Issue by NyshMy** [qb-0/pyMeow#30]
fatal.nim(54)            sysFatal
Error: unhandled exception: value out of range: 4287627008 notin -2147483648 .. 2147483647 [RangeDefect]

I want to know what caused this error

**Comment by NyshMy** [comment]
The process has ended with an exit code of -1073741819 (0xC0000005)

Will closing the handle and reopening it after each call result in such an exception

**Comment by qb-0** [comment]
A RangeDefect happens when you call a function with a to high or to low parameter. You didn't provided any code so I don't know which one caused the issue. 

```nim
nim> high(int32)
2147483647 == type int32
nim> low(int32)
-2147483648 == type int32
```

You can always activate the `debug` parameter on `open_process` to check out which call causes the trouble.

**Comment by NyshMy** [comment]
def r_int(self,addr):
        return pyMeow.r_int(self.Process, addr)

    def r_int64(self,addr):
        return pyMeow.r_int64(self.Process, addr)

This is my encapsulated call for reading integers and reading long integers

**Comment by NyshMy** [comment]
line 2: [R] [int32] 0x0000000140000000 -> 9460301
	line 3: [R] [int32] 0x0000000149E68EB4 -> 996223544
	line 11: [R] [int32] 0x000000013FCA05EC -> 73185352
	line 14: [W] [int32] 0x000000013FCA045C -> 1
	line 15: [R] [int32] 0x000000013FCA045C -> 3
	line 19: [R] [int32] 0x000000013FCA05EC -> 73185352
	line 22: [W] [int32] 0x000000013FCA045C -> 1
	line 23: [R] [int32] 0x000000013FCA045C -> 3
	line 27: [R] [int32] 0x000000013FCA05EC -> 73185352
	line 30: [W] [int32] 0x000000013FCA045C -> 1
	line 31: [R] [int32] 0x000000013FCA045C -> 3
	line 42: [W] [int32] 0x000000007B315B0C -> 200
	line 44: [W] [int32] 0x000000007B315B10 -> 200
	line 46: [W] [int32] 0x000000007B315B14 -> 200
	line 48: [W] [int32] 0x000000007B315B18 -> 200
	line 52: [R] [int32] 0x000000013FCA05EC -> 73185352
	line 55: [W] [int32] 0x000000013FCA045C -> 1
	line 56: [R] [int32] 0x000000013FCA045C -> 3
	line 60: [R] [int32] 0x000000013FCA05EC -> 73185352
	line 63: [W] [int32] 0x000000013FCA045C -> 1
	line 64: [R] [int32] 0x000000013FCA045C -> 3
	line 68: [R] [int32] 0x000000013FCA05EC -> 73185352
	line 71: [W] [int32] 0x000000013FCA045C -> 1
	line 72: [R] [int32] 0x000000013FCA045C -> 3
	line 76: [R] [int32] 0x000000013FCA05EC -> 73185352
	line 79: [W] [int32] 0x000000013FCA045C -> 1
	line 80: [R] [int32] 0x000000013FCA045C -> 3

As shown above, I searched and did not find any data that exceeded the boundary value

**Comment by qb-0** [comment]
Yes I don't see any reading before with that value. So it happens probably on a write call.

**Comment by NyshMy** [comment]
So is there a way to solve this problem? Is there any way to locate this problem

I tested that reading and writing alone is no problem

**Comment by NyshMy** [comment]
By the way, is this underlying language written in kernel32 or ntd's DLL

**Comment by qb-0** [comment]
pyMeow is using `ReadProcessMemory` from the kernel32 library.
Since I'm not into your code I guess the only way would be to debug it to find out which call causes the exception.

**Comment by NyshMy** [comment]
nimpy.AccessViolationDefect: Unexpected error encountered: WriteArray failed [Address: 0x000000013FCCB7FC] [Error: 299 - 仅完成部分的 ReadProcessMemory 或 WriteProcessMemory 请求。]

**Comment by qb-0** [comment]
I'll close that issue since it's pretty old. Feel free to reopen if there is still help wanted.
