### ISSUE TITLE
Enhancement's (Examples CS2 Cheat) 

### ISSUE THREAD

**Issue by ImInTheICU** [qb-0/pyMeow#35]
1. Load offsets automatically, here's an example I quickly made.
```
class Offsets:
    CS2Offsets = requests.get("https://raw.githubusercontent.com/a2x/cs2-dumper/main/generated/client.dll.json").json()
    dwEntityList = None
    dwViewMatrix = None
    dwLocalPlayerController = None
    m_iPawnHealth = int(CS2Offsets['CCSPlayerController']['data']['m_iPawnHealth']['value'])
    m_hPlayerPawn = int(CS2Offsets['CCSPlayerController']['data']['m_hPlayerPawn']['value'])
    m_iszPlayerName = int(CS2Offsets['CBasePlayerController']['data']['m_iszPlayerName']['value'])
    m_iTeamNum = int(CS2Offsets['C_BaseEntity']['data']['m_iTeamNum']['value'])
    m_vOldOrigin = int(CS2Offsets['C_BasePlayerPawn']['data']['m_vOldOrigin']['value'])
    m_pGameSceneNode = int(CS2Offsets['C_BaseEntity']['data']['m_pGameSceneNode']['value'])
    m_bPawnIsAlive = int(CS2Offsets['CCSPlayerController']['data']['m_bPawnIsAlive']['value'])
    m_pBoneArray = 480 
```
 2. Instead of checking health use the new offset `m_bPawnIsAlive` to check if their alive.
 ```
    @property
    def isalive(self):
        return pm.r_bool(self.proc, self.ptr + Offsets.m_bPawnIsAlive)
```
3. Add a render distance to prevent heavy load ( i had major problems with running this on an RTX3060 barely reaching 60 FPS at some points )
4. Add a health bar on the side of the ESP-box ( not possible with how pyMeow currently works, from my testing )

**Comment by ImInTheICU** [comment]
I'll create a PR

**Comment by ImInTheICU** [comment]
![image](https://github.com/qb-0/pyMeow/assets/111275373/6eea24a4-b4ce-4419-9fb5-68b54c1ad27b)

Disabling this fixed the overlay FPS drop.

**Comment by g0ldyy** [comment]
> Author

in my tests, it does the opposite and lags my overlay
effects are different on every machine, I suppose

**Comment by g0ldyy** [comment]
health bar is also possible
