### ISSUE TITLE
No way to free memory after allocation

### ISSUE THREAD

**Issue by jonchun** [qb-0/pyMeow#36]
Not a super high priority, but there doesn't seem to be a way to free memory after using allocate_memory

For reference, competing library seems to have this feature:
https://pymem.readthedocs.io/en/latest/_modules/pymem.html#Pymem.free

**Comment by qb-0** [comment]
https://github.com/qb-0/pyMeow/commit/6f9a5654dccad9daecf2d9fea334b2ad8d56c63c
