### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by marseilledz** [qb-0/pyMeow#39]
Antiy-AVL
Trojan/Win32.Wacatac
Arcabit
Trojan.Ceram.Gen.1
Avast
Win64:MalwareX-gen [Trj]
AVG
Win64:MalwareX-gen [Trj]
BitDefender
Trojan.Ceram.Gen.1
DeepInstinct
MALICIOUS
Emsisoft
Trojan.Ceram.Gen.1 (B)
Fortinet
W32/PossibleThreat
GData
Trojan.Ceram.Gen.1
Google
Detected
Ikarus
Trojan.Crypter
Lionic
Trojan.ZIP.Ceram.4!c
Malwarebytes
Crypt.Trojan.MSIL.DDS
MAX
Malware (ai Score=81)
MaxSecure
Trojan.Malware.10975391.susgen
McAfee
Artemis!0C77F8D55214
Panda
Trj/Chgt.AD
Skyhigh (SWG)
Artemis
Symantec
Trojan.Gen.NPE
Trellix (FireEye)
Trojan.Ceram.Gen.1
Varist
W64/ABRisk.RQDF-4655
VIPRE
Trojan.Ceram.Gen.1
Acronis (Static ML)
Undetected
AhnLab-V3
Undetected
Alibaba
Undetected
ALYac
Undetected
Avast-Mobile
Undetected
Avira (no cloud)
Undetected
Baidu
Undetected
BitDefenderTheta
Undetected
Bkav Pro
Undetected
ClamAV
Undetected
CMC
Undetected
Cynet
Undetected
DrWeb
Undetected
Elastic
Undetected
eScan
Undetected
ESET-NOD32
Undetected
Gridinsoft (no cloud)
Undetected
Jiangmin
Undetected
K7AntiVirus
Undetected
K7GW
Undetected
Kaspersky
Undetected
Kingsoft
Undetected
Microsoft
Undetected
NANO-Antivirus
Undetected
QuickHeal
Undetected
Rising
Undetected
Sangfor Engine Zero
Undetected
Sophos
Undetected
SUPERAntiSpyware
Undetected
TACHYON
Undetected
Tencent
Undetected
TrendMicro
Undetected
TrendMicro-HouseCall
Undetected
Trustlook
Undetected
VBA32
Undetected
VirIT
Undetected
ViRobot
Undetected
WithSecure
Undetected
Xcitium
Undetected
Yandex
Undetected
Zillya
Undetected
ZoneAlarm by Check Point
Undetected

**Comment by marseilledz** [comment]
dude I've been trying to install your zip file with pip for a while now but I can't because windows defender is harassing me...

**Comment by ImInTheICU** [comment]
I can assure you pyMeow is not a a trojan as @Hypnootika mentioned it's completely open sourced.
If you can't understand how to install the module/lib then what makes you think you're going to be able to use the library / module in the first place?

**Comment by qb-0** [comment]
As mentioned before pyMeow is open source. If you have concerns about the binary release just compile the source code on your own.

The windows release gets indeed flagged by some antivirus tools but that is nothing which we could change.

**Comment by ammystic** [comment]
> As mentioned before pyMeow is open source. If you have concerns about the binary release just compile the source code on your own.
> 
> The windows release gets indeed flagged by some antivirus tools but that is nothing which we could change.

i may be wrong but couldnt you send the file to the antivirus companies for them to check the code themselves?
