### ISSUE TITLE
(Linux) SIGSEGV: Illegal storage access.

### ISSUE THREAD

**Issue by leonardotessaroalves** [qb-0/pyMeow#43]
```
class CS2Esp:
    def __init__(self):
        try:
            self.proc = pm.open_process("cs2", True)
            # self.mod = pm.get_module(self.proc, "client")["base"]
        except Exception as e:
            sys.exit(e)

if __name__ == "__main__":
    esp = CS2Esp()
```

**Comment by leonardotessaroalves** [comment]
The name is cs2, the module name may can be client.so, but i still in the line before.

**Comment by qb-0** [comment]
Interesting. Which distro do you use? Also do any of these give some useful output?:
```
enum_processes(): Process (iterator)
pid_exists(pid: int): bool
process_exists(processName: string): bool
get_process_id(processName: string): int
get_process_name(pid: int): string
```

**Comment by leonardotessaroalves** [comment]
I use OpenSuse as main distro. I´ve tried to call these functions but none of then works as expected. I realized the import statement broken the application ```import pyMeow as pm```.
(installed via venv - pyMeow-1.53.36)

**Comment by qb-0** [comment]
> I use OpenSuse as main distro. I´ve tried to call these functions but none of then works as expected. I realized the import statement broken the application `import pyMeow as pm`. (installed via venv - pyMeow-1.53.36)

Did you use the release? I've compiled it on arch which might be a problem. Does it work if you compile pyMeow on your system?

@Hypnootika thank you I take a looksie into it

**Comment by leonardotessaroalves** [comment]
@qb-0 I used the release. After your suggestion, I compiled the project locally (I was only able to generate a .so file that was replaced in the pymeow folder within site-packages).
I used python 3.11 x64

**Comment by qb-0** [comment]
Mh, last thing I would try is uninstalling pyMeow via pip and importing the compiled one directly (just place the .so next to a script).

You could play with the compile options also. Replace `pyMeow.nim.cfg` with:
```
-d:release
--opt:speed
--app:lib
--cpu:amd64
--threads:on
--gc:refc
--out:"pyMeow.so"
--hint[Name]:off
--warning[UnusedImport]:off
--warning[BareExcept]:off
```

**Comment by qb-0** [comment]
Gonna close this one since there was no answer yet.
