### ISSUE TITLE
Opt out of `checkRoot` (linux)

### ISSUE THREAD

**Issue by Eein** [qb-0/pyMeow#47]
Hello!

I'm replacing some `pymem` code w/ `pyMeow`, and I ran into `checkRoot` which returned that i must be root to use a few functions. 
In my case, i'm only using `open_process`, `get_module`, and all of the various read functions.

I've separately compiled the application myself without the checks and the above functions work fine for my case but thought it might be convenient to have the root check be configurable in some way.

If you agree and have any ideas, I'd be happy to submit a PR.

**Comment by qb-0** [comment]
Hey, thanks for creating that issue.

It seems that indeed no root is necessary to access `/proc/pid/comm?  or `/proc/pid/maps`. However, I'm not so sure about `process_vm_readv` (`r_` calls) and `process_vm_writev`(`w_` calls). Have you tried it?

Feel free to create a pull request to accordingly remove the `checkRoot` calls.

**Comment by Eein** [comment]
I have not tried the process_vm_readv/process_vm_writev calls yet

I'm on NixOS on wayland so I'll need a bit to resolve the deps to get a full build working. I'll place this in my backlog.
Thanks!

**Comment by qb-0** [comment]
Thanks for the pr
