### ISSUE TITLE
Replace opcode to nop

### ISSUE THREAD

**Issue by Furkan125** [qb-0/PyMeow#5]
Hi, i find this opcode by using cheat engine: "Growtopia.exe"+33C1C4

So my question is how can i change this opcode to nop with PyMeow ?

**Comment by iProB1** [comment]
[enable]
"Growtopia.exe"+33C1C4:
db 90 90
[disable]
"Growtopia.exe"+33C1C4:
db --here check to address

**Comment by Furkan125** [comment]
Thanks for your answer but its for cheat engine. I need to do same thing with PyMeow module.

**Comment by qb-0** [comment]
Sorry for the late response. PyMeow has `nop_code` https://github.com/qb-0/PyMeow/blob/master/src/memory.nim#L173

So in your case it would be something like:
```python
import pymeow as pm
proc = pm.process_by_name("Growtopia.exe")
pm.nop_code(proc, proc["baseaddr"] + 0x33C1C4, 2)
```

**Comment by Furkan125** [comment]
> Sorry for the late response. PyMeow has `nop_code` https://github.com/qb-0/PyMeow/blob/master/src/memory.nim#L173
> 
> So in your case it would be something like:
> 
> ```python
> import pymeow as pm
> proc = pm.process_by_name("Growtopia.exe")
> pm.nop_code(proc, proc["baseaddr"] + 0x33C1C4, 2)
> ```

Thanks, also its possible to change bytes with PyMeow ?
To put it in more detail, here's how this works in cheat engine:
"Growtopia.exe"+33C1C4:
db 90 90

**Comment by qb-0** [comment]
> 
> 
> > Sorry for the late response. PyMeow has `nop_code` https://github.com/qb-0/PyMeow/blob/master/src/memory.nim#L173
> > So in your case it would be something like:
> > ```python
> > import pymeow as pm
> > proc = pm.process_by_name("Growtopia.exe")
> > pm.nop_code(proc, proc["baseaddr"] + 0x33C1C4, 2)
> > ```
> 
> Thanks, also its possible to change bytes with PyMeow ?
> To put it in more detail, here's how this works in cheat engine:
> "Growtopia.exe"+33C1C4:
> db 90 90

You can manually write bytes aswell. Either with `write_bytes` or with `patch_bytes`. `patch_bytes` changes the page protection to `PAGE_EXECUTE_READWRITE` before writing the bytes.

**Comment by Furkan125** [comment]
> > > Sorry for the late response. PyMeow has `nop_code` https://github.com/qb-0/PyMeow/blob/master/src/memory.nim#L173
> > > So in your case it would be something like:
> > > ```python
> > > import pymeow as pm
> > > proc = pm.process_by_name("Growtopia.exe")
> > > pm.nop_code(proc, proc["baseaddr"] + 0x33C1C4, 2)
> > > ```
> > 
> > 
> > Thanks, also its possible to change bytes with PyMeow ?
> > To put it in more detail, here's how this works in cheat engine:
> > "Growtopia.exe"+33C1C4:
> > db 90 90
> 
> You can manually write bytes aswell. Either with `write_bytes` or with `patch_bytes`. `patch_bytes` changes the page protection to `PAGE_EXECUTE_READWRITE` before writing the bytes.

Thanks.
