### ISSUE TITLE
[HELP] PyMeow after a while it causes artifacts on my GTX 750 TI

### ISSUE THREAD

**Issue by bread2288** [qb-0/pyMeow#50]
Windows: 10
CPU: Intel I3-10105F
GPU: GTX750Ti
How this is looking
![307933610_78595fc8d769cf71f0ef1efe34d5f551_800](https://github.com/qb-0/pyMeow/assets/151750492/61a749b3-1add-4be1-84ed-f51d1db1b8bf)
I don't know how fix that
It is happened if i used absolutely any project who use PyMeow

**Comment by qb-0** [comment]
Thank you for creating that issue. 

I don't think it's really pyMeow related code since pyMeow uses raylib (opengl -> glfw -> raylib) as it's render backend you might want to check out if you can find any help for your issue at the other communities.

**Comment by qb-0** [comment]
Feel free to reopen that issue if you can make sure that the issues is caused by pymeow.
