### ISSUE TITLE
PyMeow crashes with overlay

### ISSUE THREAD

**Issue by tomkan84** [qb-0/pyMeow#53]
Hi, I have a problem with PyMeow, more specifically about overlay.

My problem is that after around 5-6 seconds of displaying the overlay it crashes. My code looks something like this

`
    pm.overlay_init()
    pm.set_window_position(0, 0)
    pm.set_window_size(1919, 1079)

    run = True 
    while run and pm.overlay_loop():
        pm.begin_drawing()
        # drawing here
        pm.end_drawing()
   pm.overlay_close()
`

Program ends after around 5 seconds with message "Python is not responding". My suspicion is that it has something to do about handling the events by overlay window, as I have faced similar issues in the past using C++ and that was the issue with similar behavior. The fix in C++ was providing PeekMessage() call. Any help would be appreciated

I use the latest release of PyMeow and Python 3.12

**Comment by tomkan84** [comment]
Didn't work, the only fix I found was what I suggested and after adding PeekMessage (without actually handling it) after overlay_loop() and it no longer crashes.

**Comment by qb-0** [comment]
Closed since there was no answer yet.
