### ISSUE TITLE
(Linux) version `GLIBC_2.38' not found

### ISSUE THREAD

**Issue by hhoneeyy** [qb-0/pyMeow#54]
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/xxx/.local/lib/python3.10/site-packages/pyMeow/pyMeow.so)

**Comment by qb-0** [comment]
pyMeow is compiled on Manjaro, which likely uses a more recent version of GNU libc than your distribution. The solution for you is to compile pyMeow on your own distribution.

**Comment by hhoneeyy** [comment]
> pyMeow is compiled on Manjaro, which likely uses a more recent version of GNU libc than your distribution. The solution for you is to compile pyMeow on your own distribution.

so do i just compile it and thats it?

**Comment by qb-0** [comment]
Feel free to reopen if you still have issues.
