### ISSUE TITLE
nimpy.Exception: Unexpected error encountered: Module 'DNF.exe' not found

### ISSUE THREAD

**Issue by NyshMy** [qb-0/pyMeow#57]
self.Process = pyMeow.open_process('DNF.exe', debug=False)
nimpy.Exception: Unexpected error encountered: Module 'DNF.exe' not found

But I can get it through enum-processes
 {'name': 'DNF.exe', 'pid': 64524, 'debug': False, 'base': 0, 'handle': 0}
Processes can also read and write, with sufficient permissions. What is the reason for this

**Comment by NyshMy** [comment]
open_process(process: string|int,  debug: bool = false): Process  
But just need to pass a process PID or process name, I can open it normally with 32-bit programs, some x64 programs don't work, and I use CE to see if the process has permission to be accessed

**Comment by qb-0** [comment]
Related to #59
