### ISSUE TITLE
why is there fpos and normal pos, arent u supposed to do pos x y z not that?

### ISSUE THREAD

**Issue by Klapity** [qb-0/pyMeow#6]

**Comment by Klapity** [comment]
also offsets and pointers are hella outdated fix your examples bruv :/

**Comment by qb-0** [comment]
Be more precise. Which example do you mean? Windows? Linux? 
To draw a rectangle around a 2d object you need the height. That's why you need a head position and feet position.

**Comment by Klapity** [comment]
The ac_esp exanple uses old pyMeow has outdated pointers and offsets and doesnt run. I also want to know what is fpos3d and pos3d and why dont you use x y z coordinates instead of that stuff?
