### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by HyronNotEZ** [qb-0/PyMeow#6]
Hey there, 
I have this problem where I'm getting this error: ImportError: DLL load failed: %1 is not a valid Win32 application

I've checked all the things that came to my mind.
Python is 64 bit (also tried 32bit)
added Pythonpath.
Tried to import it in python cmd console and got same error.
Tried running python3.9 and 3.8.

I don't know how to fix it. 
I would have tried with different versions of PyMeow, but sadly, there is only one available.

I hope someone can help me, so I can get stared.

**Comment by qb-0** [comment]
Sorry for the late response. 

Make sure your environment variables are correct. Typing `python` into your command line should always show a python 3.9 64bit verison to work with pymeow.
