### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by d3uSCH** [qb-0/PyMeow#7]
How can I compile this lib?
I downloaded all dependencies (nimpy, nimgl, winim) but the compilation process crashes with this error:
```
Error: type mismatch: got <Vec2, PyTypeObject> but expected one of:
proc initPyNimObjectWithPyType(o: PyNimObject; typ: PyTypeObject)
  first type mismatch at position: 1
  required type for o: PyNimObject
  but expression 'o' is of type: Vec2

expression: initPyNimObjectWithPyType(o, typ)
```

**Comment by d3uSCH** [comment]
I was able to compile with this version of [nimpy](https://codeload.github.com/yglukhov/nimpy/zip/f2a70275f4fcbe69dabbdc6fdd3497ce39ff8c05)
But the overlay window is black: https://prnt.sc/1g3ton4

**Comment by d3uSCH** [comment]
Everything works with this version of [nimgl](https://github.com/nimgl/nimgl/tree/2ffe9e1d527aab6085decfbb56741276c480a5df)
¯\_(ツ)_/¯

**Comment by qb-0** [comment]
Everything should compile now with up to date nim libraries.
