### ISSUE TITLE
I got error when try to open process

### ISSUE THREAD

**Issue by Furkan125** [qb-0/PyMeow#8]
Hi, i got this error when i try to open process with Pid:
Unable to open Process
My error code:
5
I also try running cmd as administrator and running this command:
python test.py
but its still don't work.

**Comment by qb-0** [comment]
Please post the code you're using and a detailed error output

**Comment by Furkan125** [comment]
No, I got that error in only 1 process . I tried it in other processes and there was no problem. It also works when I try to open same process with Cheat Engine and it also works when I try with Memory.dll (a C# library)

**Comment by qb-0** [comment]
Could you check if that fixes the issue? If you aren't able to compile it for any reason let me know and I'll leave you a download for the compiled version.

**Comment by qb-0** [comment]
Please try https://github.com/qb-0/PyMeow/releases/tag/1.4

**Comment by Furkan125** [comment]
> So it could be a general rights issue by python for you.

Could it be a problem to use the script without compiling or maybe problem is Python version I am using? What version does PyMeow run on?

**Comment by qb-0** [comment]
Pymeow should run on all python 3 versions. But I guess switching to another version won't make a difference. If you want to contact me on discord and let me know which process causes that issues so I can test it out myself.

**Comment by Furkan125** [comment]
If you want to test process yourself: Download
