### ISSUE TITLE
Error while compiling [Error: cannot open file: x11/x]

### ISSUE THREAD

**Issue by rolexlinux** [qb-0/PyMeow#9]
So I wanted to compile PyMeow, but it failed.
[mong@MatrixPower PyMeow]$ nim c pymeow
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
Hint: used config file 'pymeow.nim.cfg' [Conf]
..........................................................
/home/mong/Downloads/PyMeow/src/linux/misc.nim(2, 10) Error: cannot open file: x11/x

**Comment by rolexlinux** [comment]
Also my distro is arch linux

**Comment by qb-0** [comment]
Dependency `x11` is required for a linux compilation. `nimble -y install x11`

Added with https://github.com/qb-0/PyMeow/commit/82dde93b9c57475f8ad92e58f5a80c166461eda9

**Comment by rolexlinux** [comment]
installing x11 thru nimble fixed the error but a new one came up
[mong@MatrixPower PyMeow]$ nim c pymeow
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
Hint: used config file 'pymeow.nim.cfg' [Conf]
........................................................................
/home/mong/Downloads/PyMeow/src/linux/overlay.nim(3, 31) Error: cannot open file: opengl/glut

was fixed using 
`nimble -y install opengl`
